### ISSUE TITLE
not correct type with dropdown fields

### ISSUE THREAD

**Issue by Jimmi08** [septor/showonpages#3]
Just change type from text to dropdown:

![image](https://cloud.githubusercontent.com/assets/5429548/11571745/25905f0c-99fe-11e5-9b3c-32ddd495c640.png)

![image](https://cloud.githubusercontent.com/assets/5429548/11571755/3b9a1efa-99fe-11e5-85a2-76866da6dc01.png)

Result:
![image](https://cloud.githubusercontent.com/assets/5429548/11571765/45b69f1c-99fe-11e5-8357-6d11e74ab592.png)

**Comment by septor** [comment]
Yeah this is already addressed on my local files. I'm working out a few things before I get back to this plugin to finish up the changes and push the code.
